name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y valgrind libbrotli-dev libsqlite3-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      run: make
